using GLMS2.Data;
using GLMS2.Interfaces;
using GLMS2.Repositories;
using GLMS2.Services;
using GLMS2.Services.Factories;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using GLMS2.Services.Mediator;

var builder = WebApplication.CreateBuilder(args);

// Controllers return JSON data for the REST API.
// Enum values are displayed as names such as "Active" instead of numbers.
builder.Services
    .AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters
            .Add(new JsonStringEnumConverter());
    });

// Generates the OpenAPI description used by Swagger UI.
builder.Services.AddOpenApi();

// API database connection.
// Only the API will remain connected to this database after the MVC refactor.
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(
        builder.Configuration.GetConnectionString("DefaultConnection")));

var jwtKey = builder.Configuration["Jwt:Key"]
    ?? throw new InvalidOperationException("Jwt:Key is missing.");

var jwtIssuer = builder.Configuration["Jwt:Issuer"]
    ?? throw new InvalidOperationException("Jwt:Issuer is missing.");

var jwtAudience = builder.Configuration["Jwt:Audience"]
    ?? throw new InvalidOperationException("Jwt:Audience is missing.");

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwtIssuer,
            ValidAudience = jwtAudience,
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(jwtKey)),
            ClockSkew = TimeSpan.Zero
        };
    });

builder.Services.AddAuthorization();

// Repository layer.
builder.Services.AddScoped<IContractRepository, ContractRepository>();
builder.Services.AddScoped<IClientRepository, ClientRepository>();

// Existing backend services and Factory pattern.
builder.Services.AddScoped<IFileService, FileService>();
builder.Services.AddScoped<IContractFactory, ContractFactory>();
builder.Services.AddScoped<IContractService, ContractService>();
builder.Services.AddScoped<IServiceRequestRepository, ServiceRequestRepository>();
builder.Services.AddScoped<IServiceRequestService, ServiceRequestService>();
builder.Services.AddScoped<IMediator, GLMSMediator>();

builder.Services.AddHttpClient<ICurrencyService, CurrencyService>();

var app = builder.Build();
await ApplyDatabaseMigrationsWithRetryAsync(app);

if (app.Environment.IsDevelopment())
{
    // OpenAPI JSON document generated by ASP.NET Core.
    app.MapOpenApi();

    // Interactive Swagger testing page.
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint(
            "/openapi/v1.json",
            "GLMS Backend API v1");

        options.RoutePrefix = "swagger";
    });
}

var runningInContainer =
    Environment.GetEnvironmentVariable("DOTNET_RUNNING_IN_CONTAINER") == "true";

if (!runningInContainer)
{
    app.UseHttpsRedirection();
}
// Allows uploaded agreement files to be stored under wwwroot.
app.UseStaticFiles();
app.UseAuthentication();

app.UseAuthorization();

app.MapGet("/health", () => Results.Ok("GLMS API is running"));
app.MapControllers();

app.Run();
static async Task ApplyDatabaseMigrationsWithRetryAsync(WebApplication app)
{
    using var scope = app.Services.CreateScope();

    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    var logger = scope.ServiceProvider
        .GetRequiredService<ILoggerFactory>()
        .CreateLogger("DatabaseMigration");

    const int maxAttempts = 10;

    for (var attempt = 1; attempt <= maxAttempts; attempt++)
    {
        try
        {
            logger.LogInformation("Applying database migrations. Attempt {Attempt}/{MaxAttempts}", attempt, maxAttempts);

            await dbContext.Database.MigrateAsync();

            logger.LogInformation("Database migrations applied successfully.");

            return;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Database migration attempt {Attempt} failed.", attempt);

            if (attempt == maxAttempts)
            {
                throw;
            }

            await Task.Delay(TimeSpan.FromSeconds(5));
        }
    }
}