using GLMS2.Data;
using GLMS2.Interfaces;
using GLMS2.Repositories;
using GLMS2.Services;
using GLMS2.Services.Factories;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using GLMS2.Services.Mediator;

var builder = WebApplication.CreateBuilder(args);

// Controllers return JSON data for the REST API.
// Enum values are displayed as names such as "Active" instead of numbers.
builder.Services
    .AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters
            .Add(new JsonStringEnumConverter());
    });

// Generates the OpenAPI description used by Swagger UI.
builder.Services.AddOpenApi();

// API database connection.
// Only the API will remain connected to this database after the MVC refactor.
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(
        builder.Configuration.GetConnectionString("DefaultConnection")));

var jwtKey = builder.Configuration["Jwt:Key"]
    ?? throw new InvalidOperationException("Jwt:Key is missing.");

var jwtIssuer = builder.Configuration["Jwt:Issuer"]
    ?? throw new InvalidOperationException("Jwt:Issuer is missing.");

var jwtAudience = builder.Configuration["Jwt:Audience"]
    ?? throw new InvalidOperationException("Jwt:Audience is missing.");

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwtIssuer,
            ValidAudience = jwtAudience,
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(jwtKey)),
            ClockSkew = TimeSpan.Zero
        };
    });

builder.Services.AddAuthorization();

// Repository layer.
builder.Services.AddScoped<IContractRepository, ContractRepository>();
builder.Services.AddScoped<IClientRepository, ClientRepository>();

// Existing backend services and Factory pattern.
builder.Services.AddScoped<IFileService, FileService>();
builder.Services.AddScoped<IContractFactory, ContractFactory>();
builder.Services.AddScoped<IContractService, ContractService>();
builder.Services.AddScoped<IServiceRequestRepository, ServiceRequestRepository>();
builder.Services.AddScoped<IServiceRequestService, ServiceRequestService>();
builder.Services.AddScoped<IMediator, GLMSMediator>();

builder.Services.AddHttpClient<ICurrencyService, CurrencyService>();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    // OpenAPI JSON document generated by ASP.NET Core.
    app.MapOpenApi();

    // Interactive Swagger testing page.
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint(
            "/openapi/v1.json",
            "GLMS Backend API v1");

        options.RoutePrefix = "swagger";
    });
}

app.UseHttpsRedirection();

// Allows uploaded agreement files to be stored under wwwroot.
app.UseStaticFiles();
app.UseAuthentication();

app.UseAuthorization();


app.MapControllers();

app.Run();